--WITH SAMSUNG_PRODUCTS AS 
--(SELECT PName 
--FROM PRODUCTS 
--WHERE maker = 'Samsung')

-- left join in order to show the product that is not even sell in all shops
--SELECT SAMSUNG_PRODUCTS.PName, COUNT(DISTINCT PRODUCTS_IN_SHOPS.SName) as No_Of_Shops 
--FROM SAMSUNG_PRODUCTS
--LEFT JOIN PRODUCTS_IN_SHOPS 
--ON PRODUCTS_IN_SHOPS.PName = SAMSUNG_PRODUCTS.PName
--GROUP BY SAMSUNG_PRODUCTS.PName;

SELECT PRODUCTS.PName AS Product, COUNT(PRODUCTS_IN_SHOPS.PName) AS No_of_Shops
FROM PRODUCTS
LEFT JOIN PRODUCTS_IN_SHOPS
ON PRODUCTS.PName = PRODUCTS_IN_SHOPS.PName
WHERE maker = 'Samsung'
GROUP BY PRODUCTS.PName;